# SPDX-License-Identifier: MIT

"""Archive skill-training artifacts newer than the recovered policy checkpoint.

AReaL resumes at the step after its last recover checkpoint and replays later
steps with the same dataloader inputs. Artifacts that the previous attempt wrote
for those steps are moved under ``recovery_rollbacks/`` and regenerated by the
replay. Failure markers and lock files left by the previous attempt are moved
with them; this runs in train.py before any workflow process exists. Each
archive is journaled, so an interrupted reconcile completes on the next launch.
"""

from __future__ import annotations

import os
import re
import socket
import time
from collections import Counter
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import psutil

from areal.utils import logging
from areal.utils.recover import InValidRecoverInfo, RecoverHandler, RecoverInfo
from areal.utils.saver import Saver
from areal.workflow.alfworld_runtime import (
    _acquire_json_lock,
    _atomic_write_json,
    _read_json,
    _release_json_lock,
    _remove_old_unreadable_lock,
)

logger = logging.getLogger("SkillTrainingRecovery")

RECOVERY_DIR = "recovery_rollbacks"
WORKFLOW_FAILURE_MARKERS = (
    "diagnostics/workflow_failure.json",
    "fatal_workflow_error.json",
)
_RECONCILE_LOCK_STALE_S = 600.0
_RECONCILE_LOCK_TIMEOUT_S = 900.0
_INDEXED_NAME = re.compile(r"^(?P<prefix>round_|globalstep_)(?P<index>\d+)(?:\..*)?$")

# (root, offset): an entry globalstep_N under root is archived when
# N >= resume_step + offset.
_STEP_INDEXED_ROOTS = (
    ("train", 0),
    ("eval", 0),
    # ALFWorld: steps/globalstep_N holds the bank before and after step N.
    ("online_skillbank/steps", 0),
    ("trajectory_pool/steps", 0),
    # A consumption marker is named by the step that deleted the previous
    # step's pool; the resume step's marker lets that pool be rebuilt from the
    # kept canonical rollouts.
    ("trajectory_pool/consumption", 1),
    # WebShop: updates/globalstep_N turns snapshot N into snapshot N + 1, so the
    # snapshot of the resume step is the recovered bank.
    ("skillbank/updates", 0),
    ("skillbank/snapshots", 1),
)


def _indexed_children(root: Path, prefix: str) -> list[tuple[int, Path]]:
    if not root.is_dir():
        return []
    children: list[tuple[int, Path]] = []
    for path in root.iterdir():
        match = _INDEXED_NAME.fullmatch(path.name)
        if match is not None and match.group("prefix") == prefix:
            children.append((int(match.group("index")), path))
    return children


def _round_is_future(
    round_index: int,
    *,
    resume_global_step: int,
    groups_per_round: int,
    train_batch_size: int,
) -> bool:
    first_step = round_index * groups_per_round // train_batch_size
    last_step = ((round_index + 1) * groups_per_round - 1) // train_batch_size
    if first_step >= resume_global_step:
        return True
    if last_step >= resume_global_step:
        raise ValueError(
            f"training round {round_index} spans optimizer steps {first_step}-"
            f"{last_step}; artifacts cannot be rolled back to step "
            f"{resume_global_step} unless train_batch_size holds whole rounds"
        )
    return False


def future_artifact_paths(
    artifact_dir: Path,
    *,
    resume_global_step: int,
    groups_per_round: int,
    train_batch_size: int,
) -> list[Path]:
    """Return artifact roots that belong to optimizer steps >= resume_global_step."""

    artifact_dir = Path(artifact_dir)
    sources: list[Path] = []
    categories = artifact_dir / "categories"
    if categories.is_dir():
        for category_root in sorted(categories.iterdir()):
            for round_index, path in _indexed_children(category_root, "round_"):
                if _round_is_future(
                    round_index,
                    resume_global_step=resume_global_step,
                    groups_per_round=groups_per_round,
                    train_batch_size=train_batch_size,
                ):
                    sources.append(path)
    for relative, offset in _STEP_INDEXED_ROOTS:
        for step, path in _indexed_children(artifact_dir / relative, "globalstep_"):
            if step >= resume_global_step + offset:
                sources.append(path)
    early_stop_path = artifact_dir / "early_stop.json"
    if early_stop_path.is_file():
        try:
            stop_step = int(_read_json(early_stop_path).get("global_step", -1))
        except Exception:
            stop_step = resume_global_step
        if stop_step >= resume_global_step:
            sources.append(early_stop_path)
    return sorted(set(sources), key=lambda path: str(path.relative_to(artifact_dir)))


def _leftover_runtime_paths(
    artifact_dir: Path, *, skip: set[Path]
) -> list[tuple[Path, str]]:
    found = [
        (artifact_dir / relative, "failure_marker")
        for relative in WORKFLOW_FAILURE_MARKERS
        if (artifact_dir / relative).is_file()
    ]
    for root, dirs, files in os.walk(artifact_dir):
        root_path = Path(root)
        dirs[:] = [
            name
            for name in dirs
            if root_path / name not in skip
            and not (root_path == artifact_dir and name == RECOVERY_DIR)
        ]
        found.extend(
            (root_path / name, "lock") for name in files if name.endswith(".lock")
        )
    return found


def _planned_sources(
    artifact_dir: Path,
    *,
    resume_global_step: int,
    groups_per_round: int,
    train_batch_size: int,
) -> list[tuple[Path, str]]:
    future = future_artifact_paths(
        artifact_dir,
        resume_global_step=resume_global_step,
        groups_per_round=groups_per_round,
        train_batch_size=train_batch_size,
    )
    planned = [(path, "future_step") for path in future]
    planned.extend(_leftover_runtime_paths(artifact_dir, skip=set(future)))
    return sorted(planned, key=lambda item: str(item[0].relative_to(artifact_dir)))


def _move_plan(
    *, artifact_dir: Path, attempt_dir: Path, planned: Sequence[tuple[Path, str]]
) -> list[dict[str, str]]:
    moves: list[dict[str, str]] = []
    for source, kind in planned:
        relative = source.relative_to(artifact_dir)
        destination = attempt_dir / "artifacts" / relative
        moves.append(
            {
                "source": str(relative),
                "destination": str(destination.relative_to(artifact_dir)),
                "kind": kind,
            }
        )
    return moves


def _next_attempt_dir(recovery_root: Path, *, resume_global_step: int) -> Path:
    resume_root = recovery_root / f"resume_globalstep_{resume_global_step:06d}"
    used: list[int] = []
    for path in resume_root.glob("attempt_*"):
        try:
            used.append(int(path.name.rsplit("_", 1)[1]))
        except (IndexError, ValueError):
            continue
    return resume_root / f"attempt_{max(used, default=0) + 1:04d}"


def _pending_journal(recovery_root: Path) -> tuple[Path, dict[str, Any]] | None:
    pending: list[tuple[Path, dict[str, Any]]] = []
    for journal_path in sorted(
        recovery_root.glob("resume_globalstep_*/attempt_*/journal.json")
    ):
        payload = _read_json(journal_path)
        if payload.get("status") == "in_progress":
            pending.append((journal_path.parent, payload))
    if len(pending) > 1:
        raise RuntimeError(
            "multiple in-progress recovery rollback journals exist: "
            f"{[str(path / 'journal.json') for path, _ in pending]}"
        )
    return pending[0] if pending else None


def _apply_journal(
    artifact_dir: Path, attempt_dir: Path, payload: dict[str, Any]
) -> list[dict[str, str]]:
    moves = list(payload.get("moves", []))
    for move in moves:
        source = artifact_dir / str(move["source"])
        destination = artifact_dir / str(move["destination"])
        if source.exists() and destination.exists():
            raise RuntimeError(
                "both source and archived artifact exist during rollback: "
                f"{source} and {destination}"
            )
        if source.exists():
            destination.parent.mkdir(parents=True, exist_ok=True)
            os.replace(source, destination)
        elif not destination.exists() and move.get("kind") != "lock":
            raise RuntimeError(
                "rollback journal references a missing source and archive: "
                f"{source} and {destination}"
            )
    _atomic_write_json(
        attempt_dir / "journal.json",
        {**payload, "status": "complete", "completed_at": time.time()},
    )
    return moves


def _clear_abandoned_reconcile_lock(lock_path: Path) -> None:
    # Only train.py startup takes this lock. A lock naming this process, or one
    # older than any reconcile, was left by an earlier attempt (possibly in a
    # restarted container that reuses PIDs).
    try:
        payload = _read_json(lock_path)
    except FileNotFoundError:
        return
    except Exception:
        payload = {}
    try:
        pid = int(payload.get("pid", -1))
    except (TypeError, ValueError):
        pid = -1
    if payload.get("host") == socket.gethostname() and pid == os.getpid():
        lock_path.unlink(missing_ok=True)
        return
    _remove_old_unreadable_lock(
        lock_path, payload.get("claimed_at"), stale_after_s=_RECONCILE_LOCK_STALE_S
    )


def _acquire_reconcile_lock(lock_path: Path) -> int:
    deadline = time.monotonic() + _RECONCILE_LOCK_TIMEOUT_S
    while True:
        _clear_abandoned_reconcile_lock(lock_path)
        try:
            return _acquire_json_lock(
                lock_path, timeout_s=30.0, foreign_host_stale_after_s=120.0
            )
        except TimeoutError:
            if time.monotonic() >= deadline:
                raise


def _previous_attempt_worker_pids(experiment_name: str, trial_name: str) -> list[int]:
    expected = {("--experiment-name", experiment_name), ("--trial-name", trial_name)}
    pids: list[int] = []
    for process in psutil.process_iter(["pid", "cmdline"]):
        cmdline = process.info.get("cmdline") or []
        if process.info["pid"] != os.getpid() and expected <= set(
            zip(cmdline, cmdline[1:])
        ):
            pids.append(int(process.info["pid"]))
    return sorted(pids)


def archive_future_artifacts(
    *,
    artifact_dir: Path,
    benchmark: str,
    resume_global_step: int,
    checkpoint_global_step: int,
    groups_per_round: int,
    train_batch_size: int,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Move artifacts of steps >= resume_global_step, failure markers, and locks aside."""

    artifact_dir = Path(artifact_dir).expanduser()
    resume_global_step = int(resume_global_step)
    checkpoint_global_step = int(checkpoint_global_step)
    groups_per_round = int(groups_per_round)
    train_batch_size = int(train_batch_size)
    if resume_global_step < 0:
        raise ValueError("resume_global_step must be non-negative")
    if resume_global_step != checkpoint_global_step + 1:
        raise ValueError("resume_global_step must equal checkpoint_global_step + 1")
    if groups_per_round <= 0 or train_batch_size <= 0:
        raise ValueError("groups_per_round and train_batch_size must be positive")

    layout = {
        "resume_global_step": resume_global_step,
        "groups_per_round": groups_per_round,
        "train_batch_size": train_batch_size,
    }
    result: dict[str, Any] = {
        "status": "clean",
        "benchmark": benchmark,
        "checkpoint_global_step": checkpoint_global_step,
        "resume_global_step": resume_global_step,
        "archive_dir": "",
        "moves": [],
    }
    if not artifact_dir.is_dir():
        return result
    recovery_root = artifact_dir / RECOVERY_DIR
    planned = _planned_sources(artifact_dir, **layout)
    if dry_run:
        attempt_dir = _next_attempt_dir(
            recovery_root, resume_global_step=resume_global_step
        )
        return {
            **result,
            "status": "dry_run",
            "archive_dir": str(attempt_dir),
            "moves": _move_plan(
                artifact_dir=artifact_dir, attempt_dir=attempt_dir, planned=planned
            ),
        }
    if not planned and _pending_journal(recovery_root) is None:
        return result

    recovery_root.mkdir(parents=True, exist_ok=True)
    lock_path = recovery_root / "reconcile.lock"
    fd = _acquire_reconcile_lock(lock_path)
    try:
        moves: list[dict[str, str]] = []
        pending = _pending_journal(recovery_root)
        if pending is not None:
            attempt_dir, payload = pending
            # Finishing it is safe when it archives a subset of the current plan.
            if int(payload.get("resume_global_step", -1)) < resume_global_step:
                raise RuntimeError(
                    "an interrupted recovery rollback targets an earlier step: "
                    f"{attempt_dir / 'journal.json'}"
                )
            moves.extend(_apply_journal(artifact_dir, attempt_dir, payload))
            result["archive_dir"] = str(attempt_dir)

        planned = _planned_sources(artifact_dir, **layout)
        if planned:
            attempt_dir = _next_attempt_dir(
                recovery_root, resume_global_step=resume_global_step
            )
            attempt_dir.mkdir(parents=True, exist_ok=False)
            payload = {
                "version": 2,
                "status": "in_progress",
                "benchmark": benchmark,
                "checkpoint_global_step": checkpoint_global_step,
                **layout,
                "moves": _move_plan(
                    artifact_dir=artifact_dir, attempt_dir=attempt_dir, planned=planned
                ),
                "created_at": time.time(),
            }
            _atomic_write_json(attempt_dir / "journal.json", payload)
            moves.extend(_apply_journal(artifact_dir, attempt_dir, payload))
            result["archive_dir"] = str(attempt_dir)
        if moves:
            result["status"] = "rolled_back"
            result["moves"] = moves
        return result
    finally:
        _release_json_lock(fd, lock_path)


def reconcile_artifacts_from_recover(
    *,
    artifact_dir: Path,
    recover_config: Any,
    benchmark: str,
    groups_per_round: int,
    train_batch_size: int,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Align artifacts with the step AReaL will resume from."""

    mode = str(getattr(recover_config, "mode", "disabled") or "disabled")
    if mode in {"disabled", "off"}:
        return {"status": "recovery_disabled", "moves": []}
    if Path(artifact_dir).expanduser().is_dir():
        # Scheduler workers are plain children of train.py; after a hard kill they
        # can outlive it and keep writing the artifacts archived here.
        pids = _previous_attempt_worker_pids(
            str(recover_config.experiment_name), str(recover_config.trial_name)
        )
        if pids:
            raise RuntimeError(
                f"processes from a previous {benchmark} attempt of this trial are "
                f"still running (pids {pids}); stop them before relaunching"
            )
    recover_info_path = Path(
        RecoverHandler.recover_info_path(
            str(recover_config.experiment_name),
            str(recover_config.trial_name),
            str(recover_config.fileroot),
        )
    )
    if recover_info_path.exists():
        try:
            recover_info = RecoverInfo.load(str(recover_info_path))
        except (FileNotFoundError, InValidRecoverInfo) as exc:
            raise RuntimeError(
                f"{benchmark} recover info exists but is invalid: {recover_info_path}; "
                "remove it to restart from step 0, or use a new trial"
            ) from exc
        if not bool(getattr(recover_config, "align_dataloader_to_step", False)):
            raise RuntimeError(
                f"{benchmark} artifact rollback requires "
                "recover.align_dataloader_to_step=true"
            )
        # AReaL restarts from step 0 if the checkpoint itself is missing, which
        # would disagree with the step kept here.
        checkpoint_dir = Path(
            Saver.get_recover_checkpoint_path(
                str(recover_config.experiment_name),
                str(recover_config.trial_name),
                str(recover_config.fileroot),
            )
        )
        if not any(checkpoint_dir.iterdir()):
            raise RuntimeError(
                f"{benchmark} recover info exists but its checkpoint is missing: "
                f"{checkpoint_dir}; remove {recover_info_path} to restart from "
                "step 0, or use a new trial"
            )
        checkpoint_step = int(recover_info.last_step_info.global_step)
        resume_step = int(recover_info.last_step_info.next().global_step)
    else:
        # Without recover info AReaL starts again from step 0.
        checkpoint_step, resume_step = -1, 0
    result = archive_future_artifacts(
        artifact_dir=artifact_dir,
        benchmark=benchmark,
        resume_global_step=resume_step,
        checkpoint_global_step=checkpoint_step,
        groups_per_round=groups_per_round,
        train_batch_size=train_batch_size,
        dry_run=dry_run,
    )
    result["recover_info_path"] = str(recover_info_path)
    if result["status"] == "rolled_back":
        logger.warning(
            "Archived %s %s artifact paths %s before resuming at step %s: %s",
            len(result["moves"]),
            benchmark,
            dict(Counter(str(move.get("kind")) for move in result["moves"])),
            resume_step,
            result["archive_dir"],
        )
    return result


__all__ = [
    "RECOVERY_DIR",
    "WORKFLOW_FAILURE_MARKERS",
    "archive_future_artifacts",
    "future_artifact_paths",
    "reconcile_artifacts_from_recover",
]
